// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmc8yXOMtts_OpNuD4neaeApPYOmvn2ns',
    appId: '1:634503482176:web:a6b4696a791ab632cd88a5',
    messagingSenderId: '634503482176',
    projectId: 'login-and-profil',
    authDomain: 'login-and-profil.firebaseapp.com',
    storageBucket: 'login-and-profil.appspot.com',
    measurementId: 'G-841MN5HK3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPHe1xOC-nNB7Nr5vMGXp-w6Xq28ZqGYM',
    appId: '1:634503482176:android:05a0dd2c55d71b29cd88a5',
    messagingSenderId: '634503482176',
    projectId: 'login-and-profil',
    storageBucket: 'login-and-profil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlY0PPIFi46NRrd69b4odxgmqO4i0Yf6E',
    appId: '1:634503482176:ios:83b8f10035fc62a4cd88a5',
    messagingSenderId: '634503482176',
    projectId: 'login-and-profil',
    storageBucket: 'login-and-profil.appspot.com',
    iosClientId: '634503482176-krou35jbfg83mmsmdjf56nt71trqpdsv.apps.googleusercontent.com',
    iosBundleId: 'com.yayat.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlY0PPIFi46NRrd69b4odxgmqO4i0Yf6E',
    appId: '1:634503482176:ios:83b8f10035fc62a4cd88a5',
    messagingSenderId: '634503482176',
    projectId: 'login-and-profil',
    storageBucket: 'login-and-profil.appspot.com',
    iosClientId: '634503482176-krou35jbfg83mmsmdjf56nt71trqpdsv.apps.googleusercontent.com',
    iosBundleId: 'com.yayat.loginFirebase',
  );
}
